# symverse-shop-api
server:
  port: 8080  # Spring boot Server port

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
      username: sa
      password:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace